# langchain/default.nix generated by extract-langchain-deps.nix

{ lib
, buildPythonPackage
, fetchFromGitHub
, poetry-core
, pydantic
, sqlalchemy
, requests
, pyyaml
, numpy
, openapi-schema-pydantic
, dataclasses-json
, tenacity
, aiohttp
, async-timeout
, numexpr
, langchainplus-sdk
, tqdm
, faiss
, nltk
, beautifulsoup4
, jinja2
, openai
, html2text
, pexpect
, jq
, lxml
, pandas
, chardet
, requests-toolbelt
}:

buildPythonPackage rec {
  pname = "langchain";
  version = "0.0.221";

  src = fetchFromGitHub {
    owner = "hwchase17";
    repo = "langchain";
    rev = "v${version}";
    hash = "sha256-1L9BMZFAF3oLeSEfdQiVNU+q8L1WQQ7ZQbNf0qFwFZQ=";
  };

  format = "pyproject";

  buildInputs = [
    poetry-core
  ];

  propagatedBuildInputs = let
    core = [
      pydantic
      sqlalchemy
      requests
      pyyaml
      numpy
      openapi-schema-pydantic
      dataclasses-json
      tenacity
      aiohttp
      async-timeout
      numexpr
      langchainplus-sdk

    ];

    core-utils = [
      tqdm
      (faiss.override { cudaSupport = false; })
      nltk
      beautifulsoup4
      jinja2
      openai
      html2text
      pexpect
      jq
      lxml
      pandas
      chardet
      requests-toolbelt

    ];
  in core ++ core-utils;

  pythonImportsCheck = [
    "langchain"
  ];

  meta = with lib; {
    description = ''
      Building applications with LLMs through composability
    '';
    homepage = "https://docs.langchain.com/docs/";
    license = licenses.mit;
    maintainers = with maintainers; [ breakds ];
  };
}
