# This file is modified from a draft generated by the following command
# nix run .#pyproj2nix /home/breakds/projects/other/sglang/python/pyproject.toml

{ lib
, buildPythonPackage
, fetchFromGitHub
, packaging
, modelscope
, openai
, torch
, aiohttp
, ipython
, llguidance
, huggingface-hub
, tiktoken
, anthropic
, uvloop
, soundfile
, psutil
, pyzmq
, sglang
, accelerate
, hf-transfer
, multipart
, requests
, cuda-python
, xgrammar
, setuptools
, litellm
, setproctitle
, pandas
, blobfile
, prometheus-client
, pynvml
, pillow
, flashinfer_python
, numpy
, interegular
, uvicorn
, einops
, compressed-tensors
, ninja
, jsonlines
, torchvision
, datasets
, pydantic
, tqdm
, partial_json_parser
, sgl-kernel
, transformers
, outlines
, orjson
, matplotlib
, peft
, sentence-transformers
, fastapi
}:

let
  pname = "sglang";
  version = "0.4.6.post4";

in buildPythonPackage {
  inherit pname version;
  pyproject = true;

  src = fetchFromGitHub {
    owner = "?";
    repo = "?";
    rev = version;
    hash = null;
  };

  build-system = [
    setuptools
  ];

  dependencies = [
    aiohttp
    requests
    tqdm
    numpy
    ipython
    setproctitle
  ] ++ [
    openai
    tiktoken
    anthropic
    litellm
    # torch_memory_saver
  ] ++ (with optional-dependencies; srt ++ runtime_common);

  optional-dependencies = {
    runtime_common = [
      packaging
      modelscope
      llguidance
      huggingface-hub
      soundfile
      uvloop
      psutil
      pyzmq
      hf-transfer
      multipart
      xgrammar
      blobfile
      prometheus-client
      pynvml
      pillow
      interegular
      uvicorn
      compressed-tensors
      ninja
      datasets
      pydantic
      # decord
      # torchao
      partial_json_parser
      transformers
      orjson
      fastapi
    ];
    srt = [
      flashinfer_python
      torch
      cuda-python
      einops
      sgl-kernel
      outlines
      torchvision
    ];
  };

  pythonImportsCheck = [ "sglang" ];

  meta = with lib; {
    homepage = "https://github.com/sgl-project/sglang";
    description = ''
      SGLang is yet another fast serving framework for large language models
      and vision language models.
    '';
    license = licenses.asl20;
    maintainers = with maintainers; [ breakds ];
  };
}
