
# This file is modified from a draft generated by the following command
# nix run .#pyproj2nix /home/breakds/projects/other/sglang/sgl-kernel/pyproject.toml

{ lib
, buildPythonPackage
, fetchFromGitHub
, scikit-build-core
}:

let
  pname = "sgl-kernel";
  version = "0.1.2.post1";

in buildPythonPackage {
  inherit pname version;
  pyproject = true;

  src = fetchFromGitHub {
    owner = "?";
    repo = "?";
    rev = version;
    hash = null;
  };

  build-system = [
    scikit-build-core
  ];

  dependencies = [
  ];

  optional-dependencies = {
  };

  pythonImportsCheck = [ "sgl-kernel" ];

  meta = with lib; {
    homepage = "https://github.com/sgl-project/sglang/tree/main/sgl-kernel";
    description = "Kernel Library for SGLang";
    license = ?;
    maintainers = with maintainers; [ breakds ];
  };
}

